# Build stage
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Serve stage
FROM nginx:alpine

# Xóa cấu hình default của nginx
RUN rm -rf /usr/share/nginx/html/*

# Copy file build vào thư mục public của nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Copy cấu hình nginx nếu bạn có
# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
